version: "2"

services:
    web:
        build: .
        image: devpi-dpe
        volumes:
            - ./data/devpi:/data
        environment:
            DEVPI_PASSWORD: test
            #OUTSIDE_URL: http://devpi.mydomain.com
    nginx:
        image: apsl/devpi-nginx
        links:
            - web:devpi
        volumes_from:
            - web
        ports:
            - "4040:80"
        
